### ISSUE TITLE
Use tokio::executor::spawn instead of hyper's one

### ISSUE THREAD

**Issue by ark0f** [tg-rs/tgbot#37] opened 2019-03-14 13:27 UTC
[Here](https://github.com/tg-rs/tgbot/blob/f65a26ee46121e8ab38d03ed526353424248766e/src/handler/queue.rs#L3)

**Comment by rossnomann** [comment] 2019-03-14 13:34
Duplicate of #32

**Closed by rossnomann** 2019-03-14 13:34 UTC
Labels: good first issue
